export const GET_BOOKS = "GET_BOOKS"
export const DELETE_BOOK = "DELETE_BOOK"
export const ADD_BOOK = "ADD_BOOK"
export const UPDATE_BOOK = "UPDATE_BOOK"
export const GET_SINGLE_BOOK = "GET_SINGLE_BOOK "
export const SET_BOOKS = "SET_BOOKS"